### ISSUE TITLE
Typo Q&A Judging points and Style Scale

### ISSUE THREAD

**Issue by bdelbosc** [cidermead/bjcp-api#5]
Hi, I noticed 2 mistakes on the 124 TF questions provided in the Study Guide:

"Judging at homebrew competitions is the only way to earn BJCP judging points." the answer should be false.
-> https://github.com/cidermead/bjcp-api/blob/75d876f1b1b72b86bef0415f940f8e65e5688a6c/db/migration/questions/beer-questions-db.json#L1436

"You should always fill out the “Style Scales” on the scoresheet, as a good check against your scores." the answer should be true.
-> https://github.com/cidermead/bjcp-api/blob/master/db/migration/questions/beer-questions-db.json#L908

I now have some doubts about the reliability of the other questions and answers

Cheers.

**Comment by cidermead** [comment]
Thank you for the catch. Of course, there are typos. Adding questions to a question pool in the middle of the night is another the best idea. I will have re-check every question prior to officially releasing it. It is still in demo.
