### ISSUE TITLE
Typo Q&A α-amylase

### ISSUE THREAD

**Issue by bdelbosc** [cidermead/bjcp-api#6]
"Mashing temperatures below 155 °F (68 °C) favor α-amylase, producing a more dextrinous wort. " should be FALSE

https://github.com/cidermead/bjcp-api/blob/75d876f1b1b72b86bef0415f940f8e65e5688a6c/db/migration/questions/beer-questions-db.json#L1671

"Mashing temperatures above 155°F (68°C) favor α-amylase, producing a more dextrinous wort." should be TRUE

**Comment by cidermead** [comment]
In this case, 0 does not mean false. 0 means that it is a first element of the array from the options. 

```
{
"options": [
      "true",
      "false"
    ],
    "answer": 0
}
```

Thus, it `["true", "false"][0]` which is `true`.

Closing the ticket.

**Comment by bdelbosc** [comment]
Sorry, my ticket was not clear enough, I have created #11 and #12 instead.
