### ISSUE TITLE
Typo Q&A Certified Judge

### ISSUE THREAD

**Issue by bdelbosc** [cidermead/bjcp-api#7]
"To become a BJCP Certified judge, it is sufficient to pass the Entrance Exam, score at least 70% on the Beer Judging Exam and earn 5 judging points." should be FALSE,
only half of the 5 points must be judging point AFAIU.

https://github.com/cidermead/bjcp-api/blob/75d876f1b1b72b86bef0415f940f8e65e5688a6c/db/migration/questions/beer-questions-db.json#L1131

**Comment by cidermead** [comment]
Nothing wrong with this question. Referencing "https://bjcp.org/docs/BJCP_Study_Guide.pdf" question number 95 on page 28. 

Rephrasing this question... if you pass the exam with 70 points and already have 5 points from judging competitions, would that be enough to gain a rank of Certified Judge?  The answer is "Yes".
