### ISSUE TITLE
Typo Q&A BJCP National

### ISSUE THREAD

**Issue by bdelbosc** [cidermead/bjcp-api#8]
"To become a BJCP National judge, it is sufficient to score 80% on the Beer Judging Exam and accumulate 20 experience points, with at least half of them from judging." should be TRUE
 
https://github.com/cidermead/bjcp-api/blob/75d876f1b1b72b86bef0415f940f8e65e5688a6c/db/migration/questions/beer-questions-db.json#L1167

**Comment by cidermead** [comment]
The answer to this is false. 

Reference: https://bjcp.org/docs/BJCP_Study_Guide.pdf. Page 28, question 99. 

Explanation: it is not enought just to pass the tasting exam with 80%. You also must take a writtene exam and have your average score to be 80% or above. For example, if you score 83% on the tasting, and score 78% on the written exam, the average score (rounded up) would be 81%. With 20 experience points and 10 of which are from judging would make you a National Rank Judge. 

Closing the issue.
